config/routes.rb
Javelin::Application.routes.draw do

  resources :users do
    resources :microposts, :only => [:index]

    member do
      get :following, :followers
    end
  end

  resources :sessions,            :only => [:new, :create, :destroy]
  resources :microposts,          :only => [:create, :destroy]
  resources :user_relationships,  :only => [:create, :destroy]

  match '/contact',       :to => 'pages#contact'
  match '/about',         :to => 'pages#about'
  match '/help',          :to => 'pages#help'
  match '/signup',        :to => 'users#new'
  match '/signin',        :to => 'sessions#new'
  match '/signout',       :to => 'sessions#destroy'

 # get "pages/home"
 # get "pages/about"
 # get "pages/contact"

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => "welcome#index"
  root :to => 'pages#home'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/views/layouts/_footer.html.haml
%footer
  %nav{ :id => "footer_nav" }
    %ul
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path
      %li= link_to "News", "http://news.railstutorial.org/"
      %li= link_to "Rails Tutorial", "http://www.railstutorial.org/"

app/views/layouts/_header.html.haml
%header
  / = link_to logo, root_path
  %h1{ :id => "page_title"} Random Musings
  %br
  %nav{ :id => "site_nav"}
    %ul
      %li= link_to "Home", root_path
      - if signed_in?
        %li= link_to "Users", users_path
        %li= link_to "Profile", current_user
        %li= link_to "Settings", edit_user_path(current_user)
      %li= link_to "Help", help_path
      - if signed_in?
        %li= link_to "Sign out", signout_path, :method => :delete
      - else
        %li= link_to "Sign in", signin_path
  %br

app/views/layouts/_stylesheets.html.haml
/  /[if lt IE 9]
/    %script{:type => "text/javascript",
/          :src  => "http://html5shiv.googlecode.com/svn/trunk/html5.js"}
/  = stylesheet_link_tag 'blueprint/screen', :media => 'screen'
/  = stylesheet_link_tag 'blueprint/print',  :media => 'print'
/  /[if lt IE 8]
/    = stylesheet_link_tag 'blueprint/ie'
/  = stylesheet_link_tag 'custom', :media => 'screen'

= stylesheet_link_tag 'compiled/screen.css', :media => 'screen, projection'
= stylesheet_link_tag 'compiled/print.css', :media => 'print'
/[if IE]
  = stylesheet_link_tag 'compiled/ie.css', :media => 'screen, projection'

/[if lt IE 7]
  = stylesheet_link_tag 'compiled/ie6.css', :media => 'screen, projection'

/ = stylesheet_link_tag 'compiled/sample.css', :media => 'screen'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= title
    = csrf_meta_tag
    = render 'layouts/stylesheets'
    = javascript_include_tag :defaults
  %body
    .container
      = render 'layouts/header'
      %section{ :class => "main" }
        - flash.each do |key, value|
          = content_tag(:div, value, :class => "flash #{key}")

        = yield
      = render 'layouts/footer'
      %br
      = debug(params) if Rails.env.development?